export const mySkills = [
  "angularjs.png",
  "blender.png",
  "bootstrap.png",
  "css3.png",
  "express.png",
  "html5.png",
  "illustrator.png",
  "indesign.png",
  "java.png",
  "javascript.png",
  "mysql.png",
  "nodejs.png",
  "photoshop.png",
  "react.png",
  "service_now_developer.png",
];
